# Generated by Django 5.0 on 2023-12-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='department',
        ),
    ]
