# Generated by Django 5.0 on 2023-12-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0006_alter_department_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='media/emp_id_proofs/'),
        ),
    ]
