# Generated by Django 5.0 on 2023-12-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0007_alter_employee_emp_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id_proof',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
