# Generated by Django 5.0 on 2023-12-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0008_alter_employee_emp_id_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='amount',
            new_name='deduction',
        ),
        migrations.AddField(
            model_name='salary',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
