# Generated by Django 5.0 on 2023-12-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0009_rename_amount_salary_deduction_salary_gross_amount_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email_constraint'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('contact',), name='unique_contact_constraint'),
        ),
    ]
