# Generated by Django 5.0 on 2023-12-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0010_employee_unique_email_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
